### PR TITLE
Add perWeek() interval

### PR DESCRIPTION
**Pull request by marcoboers**
This PR implements the perWeek() interval.

Related to #7

### CODE REVIEW

**Comment by Larsklopstra** [comment]
The behavior Postgresql returns isn't expected, according to the docs:

>  week of month (1–5) (the first week starts on the first day of the month)

This will result in duplicate keys

**Comment by Larsklopstra** [comment]
Will close this for now

**Comment by jtomek** [comment]
That's a pity.

**Comment by ziming** [comment]
@Larsklopstra is it fine to merge this but throw an exception if the site is using postgres driver?

This will allow us MySQL users to use it.

**Comment by mberneis** [comment]
+1 here - I need a week interval as well

**Comment by jtomek** [comment]
I don't have the resources to dig into this right not, but Chatgepete suggested this:

― ChatGPT 4: 

The issue arises with PostgreSQL's interpretation of the week. PostgreSQL's date format YYYY-W returns the week of the month, which can lead to duplicate keys because multiple months may have the same 'week number' (e.g., the first week of January and the first week of February would both be week 1).

To resolve this and ensure each week is uniquely identified, you might consider using a format that combines the year and the week of the year instead of the week of the month. PostgreSQL supports the IW format for the ISO week number and the IYYY format for the ISO week-numbering year. Using this combination ensures that each week is uniquely identified across years.

**You could change the PostgreSQL format string in PgsqlAdapter.php from 'YYYY-W' to 'IYYY-IW'.** This format respects the ISO-8601 definition of a week: starting on Monday and belonging to the year that contains the majority of its days.

Make sure to test this change thoroughly, as the interpretation of weeks can differ between systems, and ensure that it aligns with the requirements of your application and the expectations of its users.

― 

What do you think?

**Comment by danswiser** [comment]
@Larsklopstra

I can't speak for others but I would expect perWeek() to use the calendar week instead of the month week anyway.

Unless there's a majority that are actually looking for the week number of a month (1-5) then it sounds like we'd be fine implementing the previous comment suggestions.

**Comment by schmeits** [comment]
@Larsklopstra if you change the formatter of the week to "IYYY-IW" for PgSQL it's working fine... 

See the docs: 
IW | Week number of ISO 8601 week-numbering year (01-53; the first Thursday of the year is in week 1)
IYYY | ISO 8601 week-numbering year (4 or more digits)

**Comment by marcoboers** [comment]
I added the PostgreSQL fix in https://github.com/Flowframe/laravel-trend/pull/63

**Pull request closed without merging**
