### PR TITLE
Add quarter interval (MySQL & PostgreSQL)

### PR DESCRIPTION
**Pull request by d8vjork**
Didn't manage to work around SQLite maybe someone can give a ✋  on this?

For the rest tested and working, a little bit "hacky" but "justworks"

### CODE REVIEW

**Comment by Larsklopstra** [comment]
Thanks for the effort, it's a bit too hacky. New version should support adding your own intervals

**Comment by malle-pietje** [comment]
> Thanks for the effort, it's a bit too hacky. New version should support adding your own intervals

Very much like this package! Thanks for your time and effort maintaining this👍

I’m also looking for the ability to implement custom intervals such as quarter. When do you expect the new version will be available where this available? For now I’m post-processing the results from the Trend output, but a cleaner implementation would be great!

**Comment by malle-pietje** [comment]
> > Thanks for the effort, it's a bit too hacky. New version should support adding your own intervals
> 
> Very much like this package! Thanks for your time and effort maintaining this👍
> 
> I’m also looking for the ability to implement custom intervals such as quarter. When do you expect the new version will be available where this available? For now I’m post-processing the results from the Trend output, but a cleaner implementation would be great!

For those looking for a temporary solution, this method will post-process a monthly Trend and return a collection containing "Quarterly" aggregates.

```php
    /**
     * Process Trend collection to summarize aggregate values per quarter.
     *
     * @param Collection $trend
     * @return Collection
     */
    function summarizeByQuarter(Collection $trend): Collection
    {
        return $trend->groupBy(function ($item) {
            // Parse the date and determine the quarter
            $month   = (int)substr($item->date, 5, 2);
            $year    = substr($item->date, 0, 4);
            $quarter = ceil($month / 3);
            return "{$year}-Q{$quarter}"; // Format date as YYYY-QX
        })->map(function ($items, $quarter) {
            // Sum all aggregate values within the quarter group
            $totalAggregate = $items->sum('aggregate');
            return [
                'date'      => $quarter,
                'aggregate' => $totalAggregate,
            ];
        })->values(); // Re-index the collection
    }
    ```
    
Work quite well so far when using Filamentphp Charts (uses ChartJS).

**Comment by d8vjork** [comment]
@malle-pietje That's a great example, although for the amount of data I'm working on I shouldn't do that

I will maintain the fork for now until we've a way to extend this package

**Pull request closed without merging**
