### PR TITLE
Laravel 10 Support

### PR DESCRIPTION
**Pull request by ziming**

### CODE REVIEW

**Comment by ziming** [comment]
Thanks for the suggestion, i made the change

**Comment by freekmurze** [comment]
Thanks, hoping for a speedy merge 🤞

**Comment by Larsklopstra** [comment]
Fixed by Laravel Shift :)

**Comment by ziming** [comment]
My PR is earlier T.T but okay. Glad to see it merged, I holded off from using this package because I fear it is abandoned earlier

**Pull request closed without merging**
