### PR TITLE
Sort DatePeriod after merge and unique

### PR DESCRIPTION
**Pull request by Wit3**
Add Sort Collection

### CODE REVIEW

**Comment by dvigueras** [comment]
+1 to this PR. This solves a bug after merging values

**Comment by zepfietje** [comment]
Can confirm this PR indeed fixes https://github.com/Flowframe/laravel-trend/issues/3.

@Larsklopstra can you merge this?

**Comment by Larsklopstra** [comment]
Done :)

**Comment by zepfietje** [comment]
Awesome, thanks!

**Pull request merged**
