### PR TITLE
Added driver to support for Sql Server

### PR DESCRIPTION
**Pull request by tjodalv**
I've created driver for the SQL server and updated readme file to document driver support.

### CODE REVIEW

**Comment by tjodalv** [comment]
I just saw that there is another pull request that adds support for SQL server. Still, I think this one is better because this one is using CONVERT SQLserver function to format date column and the other one is using FORMAT function which is slower and locale aware. Also the other pull request unnecessary refactor code in Trend service IMO.

**Comment by ryanmortier** [comment]
I don't think this is working?

I tried your fork today and this is the SQL that was generated:

```sql
SELECT
  CONVERT(VARCHAR, created_at, 23) AS date,
  count(*) AS aggregate
FROM
  [ crm ].[ account_notes ]
WHERE
  [ created_at ] BETWEEN 2024 -03 -12 01: 59: 02.687
  AND 2024 -03 -19 01: 59: 02.687
GROUP BY
  [ CONVERT(VARCHAR, created_at, 23) ]
ORDER BY
  [ date ] ASC
```

> Query 1 ERROR at Line 1: : Msg: 102, Line 7, State: 1, Level: 15
Incorrect syntax near '01'.

**Comment by tjodalv** [comment]
I've fixed the problem with groupBy clause when using SQL server driver and tested it agains SQL Server 2022. It should work fine now.

**Comment by ryanmortier** [comment]
Working now, thanks!

```sql
SELECT
	CONVERT(VARCHAR, created_at, 23) AS date,
	count(*) AS aggregate
FROM
	[crm].[tickets]
WHERE
	[created_at] BETWEEN '2024-03-12 12:29:28.806'
	AND '2024-03-19 12:29:28.806'
GROUP BY
	CONVERT(VARCHAR, created_at, 23)
ORDER BY
	[date] ASC
```

**Comment by ryanmortier** [comment]
> I've push latest commit that encloses date column name in square brackets.

Tested and working great, thanks!

```sql
SELECT
	LEFT(CONVERT(VARCHAR, [add_date], 23), 7) AS date,
	sum(scale_quantity) AS aggregate
FROM
	[crm].[tickets]
WHERE
	[commodity_id] = 'corn'
	AND [add_date] BETWEEN '2023-03-19 20:35:42.983'
	AND '2024-03-19 20:35:42.983'
GROUP BY
	LEFT(CONVERT(VARCHAR, [add_date], 23), 7)
ORDER BY
	[date] ASC
```

@Larsklopstra can we have this reviewed and merged whenever you have a chance?

**Comment by ryanmortier** [comment]
I got looking at this today again and I started wondering if this could potentially be vulnerable to SQL injection if the developer for some reason accepted input for the `->dateColumn()` method?

**Comment by Larsklopstra** [comment]
Sorry, I won't be support Sql Server OOTB. The new extensible version will allow you to add your own drivers

**Comment by henryavila** [comment]
Please, Add support for Sql Server

**Comment by ryanmortier** [comment]
> Sorry, I won't be support Sql Server OOTB. The new extensible version will allow you to add your own drivers

What is the "new extensible version"?

**Comment by tjodalv** [comment]
You can always use my fork where sqlserver support is available or make your own fork and use that.

**Comment by kokoshneta** [comment]
> Sorry, I won't be support Sql Server OOTB. The new extensible version will allow you to add your own drivers

I asked this before when my similar PR was rejected, but never got a reply: **why not?**

The _Drivers_ section on the main doc page in the repo says, “We _currently_ support four drivers” (my emphasis), which implies that further drivers are welcome/desired, so what’s wrong with adding support for SQL Server?

If a new ‘extensible’ version is underway where users can add their own drivers, that’s all fine and good… but it will have to also address the issue address in both this an #39 that the core class uses syntax which is only supported in some SQLs (viz., grouping by a column alias), by handing off some things to the drivers.

**Pull request closed without merging**
