### PR TITLE
Add support for SQL Server

### PR DESCRIPTION
**Pull request by kokoshneta**
Add support for SQL Server

- Add SqlServerAdapter
- Refactor some functions in the base class to get around the limitation that SQL Server does not support grouping by a column alias, requiring instead a repetition of the calculation
- Update readme file

(Updated from #35 to include changes to documentation.)

### CODE REVIEW

**Comment by saulens22** [comment]
I can confirm this is indeed working with SQL Server.

**Comment by FFasna** [comment]
Thanks for the PR, it greatly worked on SQL Server

**Comment by brianglz** [comment]
Gracias por el aporte, definitivamente una excelente comunidad.

**Comment by dojazdowka** [comment]
Work on Sql Server, nice job

**Comment by ryanmortier** [comment]
Can this be merged?

**Comment by Larsklopstra** [comment]
Sorry, won't be supporting this OOTB

**Comment by kokoshneta** [comment]
> Sorry, won't be supporting this OOTB

Any particular reason for that?

**Pull request closed without merging**
